### ISSUE TITLE
Post-update hook

### ISSUE THREAD

**Issue by Nodens-** [CMiksche/gitea-auto-update#25]
It would be nice if there was a post update hook option in the settings so we could enter a command to run after successfully updating gitea. Currently I use a systemd daily timer unit to run the updater so I'm just doing a post there of `systemctl restart gitea`. The downside is that this restarts gitea regardless on if an update was performed or not which may cause issues if someone is currently interacting with a repo far more often than it should.

**Comment by CMiksche** [comment]
It already executes `systemctl start gitea.service` after the update.

So your `systemctl restart gitea` shouldn't be necessary...

**Comment by Nodens-** [comment]
Ahh my systemd unit for gitea is not actually called gitea because I run 3 instances of it on the server. That was for example's sake. I guess that was why it was not restarting. I tested with renaming the unit file and now it does. Still it should be a good option for handling cases like this or running scripts after the update. Even pre hooks for backing up etc.

**Comment by CMiksche** [comment]
I've added pre & post-update hooks to my new auto-update-solution https://chapati.systems/autoupdate/ (Which also supports various other software besides Gitea)

Because I personally focus on bringing new features to my paid Autoupdate tool, it is unlikely that I will add any new features to this project but I would approve PRs from others if anyone feels like enhancing this tool. For now I will close this Issue because of this reason.
