### ISSUE TITLE
Source Directory

### ISSUE THREAD

**Issue by P1xelC0da** [CMiksche/gitea-auto-update#29]
I have this so far:
```
[Gitea]
site=https://git.codifyde.org/api/v1/version
apiUrl=https://api.github.com/repos/go-gitea/gitea/releases/latest
system=linux-amd64
file=/usr/local/bin/gitea
tmpDir=/tmp/
buildFromSource=None
sourceDir=
logFile=update.log
```

Where can I locate the `sourceDir` for this? Am wanting to update Gitea.

**Comment by CMiksche** [comment]
You only need `sourceDir` if you want to build from source. (When `buildFromSource` is set to true)

In most cases you don't need to build from source, because Gitea already provides prebuilt binaries. Then you just set the `system`, `file` and `tmpDir` settings.

But if you still want to build from source, then `sourceDir` should be set to a directory with the Gitea source code (which can be get by cloning the Gitea repo)
